//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivatesquaresWebApiNew.Persistance.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EWT_PSQNEWEntities : DbContext
    {
        public EWT_PSQNEWEntities()
            : base("name=EWT_PSQNEWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<AuthenticateLogin_Result> AuthenticateLogin(string email, string mobile, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AuthenticateLogin_Result>("AuthenticateLogin", emailParameter, mobileParameter, passwordParameter);
        }
    
        public virtual ObjectResult<ChangePassword_Result> ChangePassword(Nullable<long> userId, string oldPassword, string newPassword)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var oldPasswordParameter = oldPassword != null ?
                new ObjectParameter("OldPassword", oldPassword) :
                new ObjectParameter("OldPassword", typeof(string));
    
            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("NewPassword", newPassword) :
                new ObjectParameter("NewPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChangePassword_Result>("ChangePassword", userIdParameter, oldPasswordParameter, newPasswordParameter);
        }
    
        public virtual ObjectResult<ForgetPassword_Result> ForgetPassword(string email, string newPassword)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("NewPassword", newPassword) :
                new ObjectParameter("NewPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ForgetPassword_Result>("ForgetPassword", emailParameter, newPasswordParameter);
        }
    
        public virtual ObjectResult<GetAddress_Result> GetAddress(Nullable<long> userId, Nullable<long> id)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAddress_Result>("GetAddress", userIdParameter, idParameter);
        }
    
        public virtual ObjectResult<GetAddToCart_Result> GetAddToCart(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAddToCart_Result>("GetAddToCart", userIdParameter);
        }
    
        public virtual ObjectResult<GetAllInterest_Result> GetAllInterest()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllInterest_Result>("GetAllInterest");
        }
    
        public virtual ObjectResult<GetBusinessDetail_Result> GetBusinessDetail(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBusinessDetail_Result>("GetBusinessDetail", idParameter);
        }
    
        public virtual ObjectResult<GetChildCategory_Result> GetChildCategory(Nullable<long> productCatId)
        {
            var productCatIdParameter = productCatId.HasValue ?
                new ObjectParameter("ProductCatId", productCatId) :
                new ObjectParameter("ProductCatId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetChildCategory_Result>("GetChildCategory", productCatIdParameter);
        }
    
        public virtual ObjectResult<GetCity_Result> GetCity(Nullable<long> stateId)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCity_Result>("GetCity", stateIdParameter);
        }
    
        public virtual ObjectResult<GetCountry_Result> GetCountry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountry_Result>("GetCountry");
        }
    
        public virtual ObjectResult<GetCoupon_Result> GetCoupon(string couponCode, Nullable<long> userId)
        {
            var couponCodeParameter = couponCode != null ?
                new ObjectParameter("CouponCode", couponCode) :
                new ObjectParameter("CouponCode", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCoupon_Result>("GetCoupon", couponCodeParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetNetwork_Result> GetNetwork(Nullable<long> logInUserId)
        {
            var logInUserIdParameter = logInUserId.HasValue ?
                new ObjectParameter("LogInUserId", logInUserId) :
                new ObjectParameter("LogInUserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNetwork_Result>("GetNetwork", logInUserIdParameter);
        }
    
        public virtual ObjectResult<GetOrders_Result> GetOrders(Nullable<long> userId, Nullable<long> saleOrderId, Nullable<long> productId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var saleOrderIdParameter = saleOrderId.HasValue ?
                new ObjectParameter("SaleOrderId", saleOrderId) :
                new ObjectParameter("SaleOrderId", typeof(long));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrders_Result>("GetOrders", userIdParameter, saleOrderIdParameter, productIdParameter);
        }
    
        public virtual ObjectResult<GetPopularProductId_Result> GetPopularProductId(Nullable<long> productCatId)
        {
            var productCatIdParameter = productCatId.HasValue ?
                new ObjectParameter("ProductCatId", productCatId) :
                new ObjectParameter("ProductCatId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPopularProductId_Result>("GetPopularProductId", productCatIdParameter);
        }
    
        public virtual ObjectResult<GetProduct_Result> GetProduct(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProduct_Result>("GetProduct", userIdParameter);
        }
    
        public virtual ObjectResult<GetProductCategory_Result> GetProductCategory(Nullable<long> parentId)
        {
            var parentIdParameter = parentId.HasValue ?
                new ObjectParameter("ParentId", parentId) :
                new ObjectParameter("ParentId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductCategory_Result>("GetProductCategory", parentIdParameter);
        }
    
        public virtual ObjectResult<GetProductDetail_Result> GetProductDetail(Nullable<long> id, Nullable<long> userId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductDetail_Result>("GetProductDetail", idParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetProfession_Result> GetProfession()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProfession_Result>("GetProfession");
        }
    
        public virtual ObjectResult<GetProfessionalKeyword_Result> GetProfessionalKeyword()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProfessionalKeyword_Result>("GetProfessionalKeyword");
        }
    
        public virtual ObjectResult<GetReview_Result> GetReview(Nullable<long> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReview_Result>("GetReview", productIdParameter);
        }
    
        public virtual ObjectResult<GetSortedProducts_Result> GetSortedProducts(string sortOrder, Nullable<long> pageIndex, Nullable<long> productCatId)
        {
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(long));
    
            var productCatIdParameter = productCatId.HasValue ?
                new ObjectParameter("ProductCatId", productCatId) :
                new ObjectParameter("ProductCatId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSortedProducts_Result>("GetSortedProducts", sortOrderParameter, pageIndexParameter, productCatIdParameter);
        }
    
        public virtual ObjectResult<GetState_Result> GetState(Nullable<long> countryId)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetState_Result>("GetState", countryIdParameter);
        }
    
        public virtual ObjectResult<GetUserBusiness_Result> GetUserBusiness(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserBusiness_Result>("GetUserBusiness", userIdParameter);
        }
    
        public virtual ObjectResult<GetUserInterest_Result> GetUserInterest(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserInterest_Result>("GetUserInterest", userIdParameter);
        }
    
        public virtual ObjectResult<GetUserProfile_Result> GetUserProfile(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserProfile_Result>("GetUserProfile", userIdParameter);
        }
    
        public virtual ObjectResult<GetUsersProfileList_Result> GetUsersProfileList(Nullable<long> logInUserId)
        {
            var logInUserIdParameter = logInUserId.HasValue ?
                new ObjectParameter("LogInUserId", logInUserId) :
                new ObjectParameter("LogInUserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsersProfileList_Result>("GetUsersProfileList", logInUserIdParameter);
        }
    
        public virtual ObjectResult<GetWishlist_Result> GetWishlist(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWishlist_Result>("GetWishlist", userIdParameter);
        }
    
        public virtual ObjectResult<InterestCategories_Result> InterestCategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InterestCategories_Result>("InterestCategories");
        }
    
        public virtual ObjectResult<IsBusinessExist_Result> IsBusinessExist(string businessName)
        {
            var businessNameParameter = businessName != null ?
                new ObjectParameter("BusinessName", businessName) :
                new ObjectParameter("BusinessName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IsBusinessExist_Result>("IsBusinessExist", businessNameParameter);
        }
    
        public virtual ObjectResult<IsEmailExist_Result> IsEmailExist(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IsEmailExist_Result>("IsEmailExist", emailParameter);
        }
    
        public virtual ObjectResult<IsParentCategory_Result> IsParentCategory(Nullable<long> productCatId)
        {
            var productCatIdParameter = productCatId.HasValue ?
                new ObjectParameter("ProductCatId", productCatId) :
                new ObjectParameter("ProductCatId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IsParentCategory_Result>("IsParentCategory", productCatIdParameter);
        }
    
        public virtual ObjectResult<LoginAuthenticate_Result> LoginAuthenticate(string mobile, string oTP)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var oTPParameter = oTP != null ?
                new ObjectParameter("OTP", oTP) :
                new ObjectParameter("OTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginAuthenticate_Result>("LoginAuthenticate", mobileParameter, oTPParameter);
        }
    
        public virtual ObjectResult<RegisterNewUser_Result> RegisterNewUser(string name, string email, string mobile, string password, string registerType)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var registerTypeParameter = registerType != null ?
                new ObjectParameter("RegisterType", registerType) :
                new ObjectParameter("RegisterType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RegisterNewUser_Result>("RegisterNewUser", nameParameter, emailParameter, mobileParameter, passwordParameter, registerTypeParameter);
        }
    
        public virtual ObjectResult<RegisterUser_Result> RegisterUser(string userMobile, string operation)
        {
            var userMobileParameter = userMobile != null ?
                new ObjectParameter("UserMobile", userMobile) :
                new ObjectParameter("UserMobile", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("Operation", operation) :
                new ObjectParameter("Operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RegisterUser_Result>("RegisterUser", userMobileParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveAddress_Result> SaveAddress(Nullable<long> id, Nullable<long> userId, string name, string mobile, string pincode, string locality, string address, Nullable<long> cityId, Nullable<long> stateId, string landmark, string alternatePhone, string operation)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var pincodeParameter = pincode != null ?
                new ObjectParameter("Pincode", pincode) :
                new ObjectParameter("Pincode", typeof(string));
    
            var localityParameter = locality != null ?
                new ObjectParameter("Locality", locality) :
                new ObjectParameter("Locality", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(long));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(long));
    
            var landmarkParameter = landmark != null ?
                new ObjectParameter("Landmark", landmark) :
                new ObjectParameter("Landmark", typeof(string));
    
            var alternatePhoneParameter = alternatePhone != null ?
                new ObjectParameter("AlternatePhone", alternatePhone) :
                new ObjectParameter("AlternatePhone", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveAddress_Result>("SaveAddress", idParameter, userIdParameter, nameParameter, mobileParameter, pincodeParameter, localityParameter, addressParameter, cityIdParameter, stateIdParameter, landmarkParameter, alternatePhoneParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveAddToCart_Result> SaveAddToCart(string cartDetails, string operation)
        {
            var cartDetailsParameter = cartDetails != null ?
                new ObjectParameter("CartDetails", cartDetails) :
                new ObjectParameter("CartDetails", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("Operation", operation) :
                new ObjectParameter("Operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveAddToCart_Result>("SaveAddToCart", cartDetailsParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveBusiness_Result> SaveBusiness(Nullable<long> id, string businessName, string location, string businessLogo, Nullable<long> professionalCatId, string professionalKeyword, Nullable<long> cityId, string pinCode, Nullable<long> userId, string email, string description, string phone, Nullable<long> countryId, string website, string operation)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var businessNameParameter = businessName != null ?
                new ObjectParameter("BusinessName", businessName) :
                new ObjectParameter("BusinessName", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var businessLogoParameter = businessLogo != null ?
                new ObjectParameter("BusinessLogo", businessLogo) :
                new ObjectParameter("BusinessLogo", typeof(string));
    
            var professionalCatIdParameter = professionalCatId.HasValue ?
                new ObjectParameter("ProfessionalCatId", professionalCatId) :
                new ObjectParameter("ProfessionalCatId", typeof(long));
    
            var professionalKeywordParameter = professionalKeyword != null ?
                new ObjectParameter("ProfessionalKeyword", professionalKeyword) :
                new ObjectParameter("ProfessionalKeyword", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(long));
    
            var pinCodeParameter = pinCode != null ?
                new ObjectParameter("PinCode", pinCode) :
                new ObjectParameter("PinCode", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(long));
    
            var websiteParameter = website != null ?
                new ObjectParameter("Website", website) :
                new ObjectParameter("Website", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveBusiness_Result>("SaveBusiness", idParameter, businessNameParameter, locationParameter, businessLogoParameter, professionalCatIdParameter, professionalKeywordParameter, cityIdParameter, pinCodeParameter, userIdParameter, emailParameter, descriptionParameter, phoneParameter, countryIdParameter, websiteParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveContactUs_Result> SaveContactUs(string fullName, string mobile, string email, string message)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveContactUs_Result>("SaveContactUs", fullNameParameter, mobileParameter, emailParameter, messageParameter);
        }
    
        public virtual ObjectResult<SaveCouponHistory_Result> SaveCouponHistory(Nullable<long> couponId, Nullable<long> userId, Nullable<long> orderId, Nullable<decimal> discount, string operation)
        {
            var couponIdParameter = couponId.HasValue ?
                new ObjectParameter("CouponId", couponId) :
                new ObjectParameter("CouponId", typeof(long));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(long));
    
            var discountParameter = discount.HasValue ?
                new ObjectParameter("Discount", discount) :
                new ObjectParameter("Discount", typeof(decimal));
    
            var operationParameter = operation != null ?
                new ObjectParameter("Operation", operation) :
                new ObjectParameter("Operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveCouponHistory_Result>("SaveCouponHistory", couponIdParameter, userIdParameter, orderIdParameter, discountParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveNetwork_Result> SaveNetwork(Nullable<long> logInUserId, Nullable<long> userId, Nullable<long> userProfileId, string operation)
        {
            var logInUserIdParameter = logInUserId.HasValue ?
                new ObjectParameter("LogInUserId", logInUserId) :
                new ObjectParameter("LogInUserId", typeof(long));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var userProfileIdParameter = userProfileId.HasValue ?
                new ObjectParameter("UserProfileId", userProfileId) :
                new ObjectParameter("UserProfileId", typeof(long));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveNetwork_Result>("SaveNetwork", logInUserIdParameter, userIdParameter, userProfileIdParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveOrders_Result> SaveOrders(Nullable<long> userId, Nullable<decimal> totalDiscount, Nullable<decimal> amount, string paymentMode, string saleOrderDetail, string operation, Nullable<long> saleOrderId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var totalDiscountParameter = totalDiscount.HasValue ?
                new ObjectParameter("TotalDiscount", totalDiscount) :
                new ObjectParameter("TotalDiscount", typeof(decimal));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(decimal));
    
            var paymentModeParameter = paymentMode != null ?
                new ObjectParameter("PaymentMode", paymentMode) :
                new ObjectParameter("PaymentMode", typeof(string));
    
            var saleOrderDetailParameter = saleOrderDetail != null ?
                new ObjectParameter("SaleOrderDetail", saleOrderDetail) :
                new ObjectParameter("SaleOrderDetail", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("Operation", operation) :
                new ObjectParameter("Operation", typeof(string));
    
            var saleOrderIdParameter = saleOrderId.HasValue ?
                new ObjectParameter("SaleOrderId", saleOrderId) :
                new ObjectParameter("SaleOrderId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveOrders_Result>("SaveOrders", userIdParameter, totalDiscountParameter, amountParameter, paymentModeParameter, saleOrderDetailParameter, operationParameter, saleOrderIdParameter);
        }
    
        public virtual ObjectResult<SaveProduct_Result> SaveProduct(Nullable<long> id, string productName, Nullable<long> productCatId, string productImage, Nullable<decimal> sellingPrice, Nullable<decimal> discountPrice, Nullable<long> businessId, Nullable<long> userId, string description, string operation, string productImages)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var productCatIdParameter = productCatId.HasValue ?
                new ObjectParameter("ProductCatId", productCatId) :
                new ObjectParameter("ProductCatId", typeof(long));
    
            var productImageParameter = productImage != null ?
                new ObjectParameter("ProductImage", productImage) :
                new ObjectParameter("ProductImage", typeof(string));
    
            var sellingPriceParameter = sellingPrice.HasValue ?
                new ObjectParameter("SellingPrice", sellingPrice) :
                new ObjectParameter("SellingPrice", typeof(decimal));
    
            var discountPriceParameter = discountPrice.HasValue ?
                new ObjectParameter("DiscountPrice", discountPrice) :
                new ObjectParameter("DiscountPrice", typeof(decimal));
    
            var businessIdParameter = businessId.HasValue ?
                new ObjectParameter("BusinessId", businessId) :
                new ObjectParameter("BusinessId", typeof(long));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("Operation", operation) :
                new ObjectParameter("Operation", typeof(string));
    
            var productImagesParameter = productImages != null ?
                new ObjectParameter("ProductImages", productImages) :
                new ObjectParameter("ProductImages", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveProduct_Result>("SaveProduct", idParameter, productNameParameter, productCatIdParameter, productImageParameter, sellingPriceParameter, discountPriceParameter, businessIdParameter, userIdParameter, descriptionParameter, operationParameter, productImagesParameter);
        }
    
        public virtual ObjectResult<SaveProductImages_Result> SaveProductImages(Nullable<long> productId, string productImages, string operation)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(long));
    
            var productImagesParameter = productImages != null ?
                new ObjectParameter("ProductImages", productImages) :
                new ObjectParameter("ProductImages", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveProductImages_Result>("SaveProductImages", productIdParameter, productImagesParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveProfile_Result> SaveProfile(Nullable<long> userId, string firstName, string lastName, string profileImage, string description, string emailId, Nullable<long> professionalCatId, string title, string professionalKeyword, Nullable<long> cityId, string password, Nullable<long> genderId, Nullable<System.DateTime> dOB, string location, string phone, string pincode, Nullable<long> countryId, string officeAddress, string otherAddress, Nullable<long> interestCatId, string userInterestDetail, string userAddressDetail)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var profileImageParameter = profileImage != null ?
                new ObjectParameter("ProfileImage", profileImage) :
                new ObjectParameter("ProfileImage", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var professionalCatIdParameter = professionalCatId.HasValue ?
                new ObjectParameter("ProfessionalCatId", professionalCatId) :
                new ObjectParameter("ProfessionalCatId", typeof(long));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var professionalKeywordParameter = professionalKeyword != null ?
                new ObjectParameter("ProfessionalKeyword", professionalKeyword) :
                new ObjectParameter("ProfessionalKeyword", typeof(string));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(long));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var genderIdParameter = genderId.HasValue ?
                new ObjectParameter("GenderId", genderId) :
                new ObjectParameter("GenderId", typeof(long));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var pincodeParameter = pincode != null ?
                new ObjectParameter("Pincode", pincode) :
                new ObjectParameter("Pincode", typeof(string));
    
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(long));
    
            var officeAddressParameter = officeAddress != null ?
                new ObjectParameter("OfficeAddress", officeAddress) :
                new ObjectParameter("OfficeAddress", typeof(string));
    
            var otherAddressParameter = otherAddress != null ?
                new ObjectParameter("OtherAddress", otherAddress) :
                new ObjectParameter("OtherAddress", typeof(string));
    
            var interestCatIdParameter = interestCatId.HasValue ?
                new ObjectParameter("InterestCatId", interestCatId) :
                new ObjectParameter("InterestCatId", typeof(long));
    
            var userInterestDetailParameter = userInterestDetail != null ?
                new ObjectParameter("UserInterestDetail", userInterestDetail) :
                new ObjectParameter("UserInterestDetail", typeof(string));
    
            var userAddressDetailParameter = userAddressDetail != null ?
                new ObjectParameter("UserAddressDetail", userAddressDetail) :
                new ObjectParameter("UserAddressDetail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveProfile_Result>("SaveProfile", userIdParameter, firstNameParameter, lastNameParameter, profileImageParameter, descriptionParameter, emailIdParameter, professionalCatIdParameter, titleParameter, professionalKeywordParameter, cityIdParameter, passwordParameter, genderIdParameter, dOBParameter, locationParameter, phoneParameter, pincodeParameter, countryIdParameter, officeAddressParameter, otherAddressParameter, interestCatIdParameter, userInterestDetailParameter, userAddressDetailParameter);
        }
    
        public virtual ObjectResult<SaveReview_Result> SaveReview(Nullable<long> productId, Nullable<long> userId, Nullable<decimal> totalRating, Nullable<decimal> givenRating, string review, string operation)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(long));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var totalRatingParameter = totalRating.HasValue ?
                new ObjectParameter("TotalRating", totalRating) :
                new ObjectParameter("TotalRating", typeof(decimal));
    
            var givenRatingParameter = givenRating.HasValue ?
                new ObjectParameter("GivenRating", givenRating) :
                new ObjectParameter("GivenRating", typeof(decimal));
    
            var reviewParameter = review != null ?
                new ObjectParameter("Review", review) :
                new ObjectParameter("Review", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("Operation", operation) :
                new ObjectParameter("Operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveReview_Result>("SaveReview", productIdParameter, userIdParameter, totalRatingParameter, givenRatingParameter, reviewParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveUserForgetPasswordLink_Result> SaveUserForgetPasswordLink(string email, string operation)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveUserForgetPasswordLink_Result>("SaveUserForgetPasswordLink", emailParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveUserInterest_Result> SaveUserInterest(string userInterestDetail, string operation)
        {
            var userInterestDetailParameter = userInterestDetail != null ?
                new ObjectParameter("UserInterestDetail", userInterestDetail) :
                new ObjectParameter("UserInterestDetail", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveUserInterest_Result>("SaveUserInterest", userInterestDetailParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveUserKeyword_Result> SaveUserKeyword(string keyword, string operation)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("Keyword", keyword) :
                new ObjectParameter("Keyword", typeof(string));
    
            var operationParameter = operation != null ?
                new ObjectParameter("operation", operation) :
                new ObjectParameter("operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveUserKeyword_Result>("SaveUserKeyword", keywordParameter, operationParameter);
        }
    
        public virtual ObjectResult<SaveWishlist_Result> SaveWishlist(Nullable<long> userId, Nullable<long> productId, string operation)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(long));
    
            var operationParameter = operation != null ?
                new ObjectParameter("Operation", operation) :
                new ObjectParameter("Operation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveWishlist_Result>("SaveWishlist", userIdParameter, productIdParameter, operationParameter);
        }
    
        public virtual ObjectResult<UserInterestedCategory_Result> UserInterestedCategory(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserInterestedCategory_Result>("UserInterestedCategory", userIdParameter);
        }
    
        public virtual ObjectResult<UserProductList_Result> UserProductList(Nullable<long> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserProductList_Result>("UserProductList", userIdParameter);
        }
    }
}
